const ONLY_RUSSIAN_LETTERS_REGEX = /^[ЁёА-я]+$/;
const ONLY_ENGLISH_LETTERS_REGEX = /^[A-z]+$/;
const EMAIL_REGEX = /[^@\s]+@[^@\s]+\.[^@\s]+/;
const NUMBERS_ONLY_REGEX = /^[0-9]+$/;

export {
  ONLY_RUSSIAN_LETTERS_REGEX,
  ONLY_ENGLISH_LETTERS_REGEX,
  EMAIL_REGEX,
  NUMBERS_ONLY_REGEX,
};
